name: spikingSpatial

channels:
- conda-forge
- defaults

dependencies:
- nest-simulator=2.18
- pip
- matplotlib
- numpy
- ipykernel
- spyder-kernels
- jupyterlab
- pip:
    - jupyter
    - scikit-image